name: Build

on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - name: Install project dependencies
        run: npm install
      - name: Linter
        run: npm run lint
      - name: Build the project
        run: npm run build
